[package]
name = "slha"
version = "0.1.0"
authors = ["Torsten Weber <tweber@physik.rwth-aachen.de>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tweber12/slha-rs"

[dependencies]
error-chain = "0.11.0"

[dev-dependencies]
slha-derive = { path = "../slha-derive" }
