environment:
    matrix:
        - TARGET: x86_64-pc-windows-gnu
          RUST_VERSION: stable
        - TARGET: x86_64-pc-windows-msvc
          RUST_VERSION: stable
        - TARGET: x86_64-pc-windows-gnu
          RUST_VERSION: beta
        - TARGET: x86_64-pc-windows-gnu
          RUST_VERSION: nightly

install:
    - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - set PATH=%PATH%;C:\msys64\mingw64\bin
    - rustc -V
    - cargo -V

build: false

test_script:
    - cd slha
    - cargo build --release --target %TARGET% --verbose
    - cargo test --release --target %TARGET% --verbose
    - cd ..\slha-test
    - cargo test --release --target %TARGET% --verbose

cache:
    - C:\Users\appveyor\.cargo\registry
    - target
